# Generated by Django 3.0.5 on 2020-04-27 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
                ('kitap_adi', models.CharField(max_length=50)),
                ('alinma_tarihi', models.DateField(null=True)),
                ('kullanici', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitaplar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
