# Generated by Django 3.0.5 on 2020-04-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_zaman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zaman',
            old_name='su_an',
            new_name='tarih',
        ),
    ]
